apiVersion: apps/v1
kind: Deployment
metadata:
  name: xkapustaj-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /jka2-openapi
            - name: BASE_URL
              value: /jka2-openapi-ui